### ISSUE TITLE
Duplication of enumerations when using ParameterSets

### ISSUE THREAD

**Issue by hanneskaeufler** [modelica/ssp-standard#11]
Consider an FMU Model Description which defines:

```
  <TypeDefinitions>
    <SimpleType name="Option">
      <Enumeration>
        <Item name="Option 1" value="1" description="First option"/>
        <Item name="Option 2" value="2" description="Second option"/>
      </Enumeration>
    </SimpleType>
  </TypeDefinitions>

    <ScalarVariable>
      <ScalarVariable name="Enumeration_input" valueReference="32" causality="parameter" variability="discrete">
      <Enumeration declaredType="Option" start="1"/>
    </ScalarVariable>
```

It appears to me that in order to set a parameter value through SSP inline in the XML, I would have to re-declare the same enumeration again, such as

```
                <ssd:ParameterBindings>
                    <ssd:ParameterBinding>
                        <ssd:ParameterValues>
                            <ssv:ParameterSet version="1.0" name="Parameter-Set">
                                <ssv:Parameters>
                                    <ssv:Parameter name="Enumeration_input" description="">
                                        <ssv:Enumeration value="Option 1" name="Option"/>
                                    </ssv:Parameter>
                                </ssv:Parameters>
                                <ssv:Enumerations>
                                    <ssc:Enumeration name="Option">
                                        <ssc:Item name="Option 1" value="1"/>
                                        <ssc:Item name="Option 2" value="2"/>
                                    </ssc:Enumeration>
                                </ssv:Enumerations>
                            </ssv:ParameterSet>
                        </ssd:ParameterValues>
                    </ssd:ParameterBinding>
                </ssd:ParameterBindings>
```

This seems repetitive and error prone if done manually (which of course on can argue about).
Am I just missing a way to do this without repetition, or is this as intended?
Any pointers are appreciated, thanks!

**Comment by pmai** [comment]
There are multiple ways of handling enumerations in SSP and SSV:

- The one you show above, where the parameter definition references an enumeration specification that travels along with the SSV file. This allows for stand-alone definition, editing and checking of the SSV file, and ensures error detection, when for example, the enumeration definition of the FMU the parameters are applied to differ (e.g. due to version skew). It is especially useful for stand-alone SSV files, but can also serve a purpose when used in directly embedded SSV files.

- The other is to leave out the optional `name` attribute of the `<ssv:Enumeration>` element. In this case the interpretation of the value is left to the point of applying the parameter to an element, like an FMU. This does not allow any stand-alone error checking or editing support, but can reduce redundancy in cases were the SSV is single-use.

There is also the option of not using named enumeration items in the parameters at all, but rather hard-code the enumeration values, but that's a separate issue.

In any case one should keep in mind that SSV parameter sets are very often not single-use items, but rather applied to multiple components, including systems, hence the need to be able to declare units, enumerations, etc. in them.

One would also expect that normally tool-support is used to generate or edit SSD and SSV files, hence neither approach should be error prone on the generation side, but the redundancy of SSV-based enumeration declarations helps in keeping follow-on errors in check.
