### ISSUE TITLE
Ensure that all valid 1.0 SSP files would still be valid 2.0 files modulo version number

### ISSUE THREAD

**Issue by pmai** [modelica/ssp-standard#39]
Please add any issues found or feedback on positive findings here in this issues.

**Comment by JochenKoehler** [comment]
web meeting 2024-08-02:
Ulrich is willing to volunteer on checking

**Comment by JochenKoehler** [comment]
web meeting 2024-08-13:
Ulrich started the checking - still work in progress
Dag, Robert will send additional files to be checked to Ulrich
Any other additional files to be checked are welcome :-)

**Comment by r-heines** [comment]
I have tested with some SSP files that we created previously here at GM, no issues so far.  Basically I just changed the version number in the ssd/ssv/ssb files from "1.0" to "2.0-alpha" and validated against the latest schema from GitHub.  Let me know if there are any additional things that you would like me to check.  Due to confidentiality constraints I cannot share the actual files, but I will continue to test internally and provide feedback.

**Comment by UKiffmeier** [comment]
I checked the following collection of SSP 1.0 sample files:
-    ControlledDrivetrain\SystemStructure.ssd
-    ControlledDrivetrain_Straightened\SystemStructure.ssd
-    ControlledTemperature\SystemStructure.ssd
-    ControlledTemperature_ParallelPlants\SystemStructure.ssd
-    Example_eDrive\SystemStructure.ssd
-    Example_eDrive_Straightened\SystemStructure.ssd
-    SampleSystem\SystemStructure.ssd
-    SampleSystemSubSystem\SystemStructure.ssd
-    SampleSystemSubSystemDictionary\SystemStructure.ssd
-    SampleSystemSubSystemDictionaryInline\SystemStructure.ssd
-    SampleSystemSubSystemReuse\SystemStructure.ssd
-    SampleSystemSubSystemReuseNested\SystemStructure.ssd
-    SampleSystemVariants\SampleSystemSubSystemReuse.ssd
-    SampleSystemVariants\SampleSystemVariants.ssd
-    SampleSystemVariants\SystemStructure.ssd
-    sinus_gain\SystemStructure.ssd
-    sinus_gain\with_signaldicts.ssd
-    SubSystem\SystemStructure.ssd

Furthermore, I received some SSP examples from Dag Brück:
-   CauerLowPassAnalog.ssd
-   CClutch.ssd
	
and Robert Hällquist:
-   ECS/SystemStructure.ssd
-   pyssp-standard/example_pyssp_standard.ssv
	
I also tested some SSP exports from dSPACE SYNECT:
-    ControlledDrivetrain_SYNECT_export\SystemStructure.ssd
-    ControlledTemperature_ParallelPlants_SYNECT_export\SystemStructure.ssd
-    ControlledTemperature_SYNECT_export\SystemStructure.ssd
-    Example_eDrive_SYNECT_export\SystemStructure.ssd
-    SYNECT BE Vehicle A4\SystemStructure.ssd
-    SYNECT ControlledDrivetrain\SystemStructure.ssd
-    SYNECT Example_eDrive\SystemStructure.ssd
-	...

My approach was to use the latest SSP 2.0 Draft Schema with two modifications:
* Pattern for version attribute:  [1-2][.][0-9]+(-.+)?   --> allows to validate unmodified SSP 1.0 files.
* Additional connector kind:      unspecified            --> needed for Dags Modelica example.
	
The validation was executed with XML Spy and the Microsoft .NET 8 Validating XML Reader.

The result is:
* **There were no issues due to an incompatible change between the SSP 1.0 and SSP 2.0 schema.**
	Only exception: The version attribute, which does not allow "1.0"
* After fixing some minor issues which were not valid even with the SSP 1.0 schema, I could successfully validate all files with the SSP 1.0 schema.

So my conclusion is:
* **The SSP 2.0 schema is backward compatible to SSP 1.0**

**Comment by pmai** [comment]
Add statement on version compatibility to document.

**Comment by pmai** [comment]
Close via #50
